# Generated by Django 5.2.4 on 2025-08-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('priority', models.CharField(max_length=100)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('provider', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress_percentage', models.IntegerField(default=0)),
                ('program_url', models.URLField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skill_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_hours', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('progress_percentage', models.IntegerField(default=0)),
                ('course_url', models.URLField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.learninggoal')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.program')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.skill')),
            ],
        ),
    ]
